/*
*	getSequence
*/

/*IF sequenceName == "SEQ_PRESCRIPTION"*/
	SELECT SEQ_PRESCRIPTION.NEXTVAL 
	  FROM DUAL
/*END*/
/*IF sequenceName == "SEQ_ORDER"*/
	SELECT SEQ_ORDER.NEXTVAL 
	  FROM DUAL
/*END*/
	  /*IF sequenceName == "SEQ_REPORT"*/
	SELECT SEQ_REPORT.NEXTVAL 
	  FROM DUAL
/*END*/
	  /*IF sequenceName == "SEQ_REQUEST"*/
	SELECT SEQ_REQUEST.NEXTVAL 
	  FROM DUAL
/*END*/	 
	  /*IF sequenceName == "SEQ_RECORD"*/
	SELECT SEQ_RECORD.NEXTVAL 
	  FROM DUAL
/*END*/	  
	  /*IF sequenceName == "SEQ_PATIENT"*/
	SELECT SEQ_PATIENT.NEXTVAL 
	  FROM DUAL
/*END*/	 
	  /*IF sequenceName == "SEQ_LAB_ITEM"*/
	SELECT SEQ_LAB_ITEM.NEXTVAL 
	  FROM DUAL
/*END*/
	  /*IF sequenceName == "SEQ_EXAM_ITEM"*/
	SELECT SEQ_EXAM_ITEM.NEXTVAL 
	  FROM DUAL
/*END*/	
	  /*IF sequenceName == "SEQ_MEDICAL_IMAGING"*/
	SELECT SEQ_MEDICAL_IMAGING.NEXTVAL 
	  FROM DUAL
/*END*/	
	  /*IF sequenceName == "SEQ_NURSING_OPERATION"*/
	SELECT SEQ_NURSING_OPERATION.NEXTVAL 
	  FROM DUAL
/*END*/	  
	  /*IF sequenceName == "SEQ_PHYSICAL_EXAM"*/
	SELECT SEQ_PHYSICAL_EXAM.NEXTVAL 
	  FROM DUAL
/*END*/
	  /*IF sequenceName == "SEQ_BILLING_RECEIPT"*/
	SELECT SEQ_BILLING_RECEIPT.NEXTVAL 
	  FROM DUAL
/*END*/
	  /*IF sequenceName == "SEQ_BILLING_ITEM"*/
	SELECT SEQ_BILLING_ITEM.NEXTVAL 
	  FROM DUAL
/*END*/
	  /*IF sequenceName == "SEQ_DOCUMENT"*/
	SELECT SEQ_DOCUMENT.NEXTVAL 
	  FROM DUAL
/*END*/
	  /*IF sequenceName == "SEQ_CODE_SYSTEM"*/
	SELECT SEQ_CODE_SYSTEM.NEXTVAL 
	  FROM DUAL
/*END*/
	  /*IF sequenceName == "SEQ_ANTIBACTERIAL_DRUG"*/
	SELECT SEQ_ANTIBACTERIAL_DRUG.NEXTVAL 
	  FROM DUAL
/*END*/
	  /*IF sequenceName == "SEQ_SYSTEM_ACCOUNT_LOG"*/
	SELECT SEQ_SYSTEM_ACCOUNT_LOG.NEXTVAL 
	  FROM DUAL
/*END*/
	  /*IF sequenceName == "SEQ_DISPENSING"*/
	SELECT SEQ_DISPENSING.NEXTVAL 
	  FROM DUAL
/*END*/
	  /*IF sequenceName == "SEQ_WARNING_NOTICE"*/
	SELECT SEQ_WARNING_NOTICE.NEXTVAL 
	  FROM DUAL
/*END*/
	  	  /*IF sequenceName == "SEQ_EXAM_RESULT_ITEM"*/
	SELECT SEQ_EXAM_RESULT_ITEM.NEXTVAL 
	  FROM DUAL
/*END*/
	  /*IF sequenceName == "SEQ_EXTERNAL_SEND_BUSINESS"*/
	SELECT SEQ_EXTERNAL_SEND_BUSINESS.NEXTVAL 
	  FROM DUAL
/*END*/
	  /*IF sequenceName == "SEQ_REPORT_CONTENT"*/
	SELECT SEQ_REPORT_CONTENT.NEXTVAL 
	  FROM DUAL
/*END*/
	  /*IF sequenceName == "SEQ_EXTERNAL_SEND_RECORD"*/
	SELECT SEQ_EXTERNAL_SEND_RECORD.NEXTVAL 
	  FROM DUAL
/*END*/