/**
 * [FUN]V05-101住院视图列表中某天具体业务
 * @version 1.0, 2012/12/25  
 * @author 金鹏
 * @since 1.0 
 * 住院视图列表中某天具体业务
 */
/*IF "diagnosis".equals(itemFlag)*/
-- 诊断
SELECT DG.VISIT_SN,DG.DIAGNOSIS_SN,DG.DISEASE_CODE,DG.DISEASE_NAME,DG.DIAGNOSIS_TYPE_NAME,DG.DIAGNOSIS_DATE INPATIENT_DATE,DG.MAIN_DIAGNOSIS_FLAG,
	   DG.DIAGNOSIS_TYPE_CODE,DG.DIAGNOSTIC_DEPT_NAME,DG.DIAGNOSIS_DOCTOR_NAME,DG.UNCERTAIN_FLAG
  FROM DIAGNOSIS DG
 WHERE DG.VISIT_SN = /*visitSn*/
 	   AND DG.DIAGNOSIS_DATE BETWEEN TO_DATE(/*inpatientDate*/,'YYYY-MM-DD') AND TO_DATE(/*inpatientDate*/ || '23:59:59', 'YYYY-MM-DD HH24:MI:SS')
 	   AND DG.DELETE_FLAG = '0'
 ORDER BY DG.DIAGNOSIS_DATE DESC,DG.DIAGNOSIS_SN DESC
/*END*/

/*IF "drugOrderLong".equals(itemFlag)*/
-- 长期药物医嘱
SELECT MO.VISIT_SN,
	   MO.ORDER_SN,
	   MO.DRUG_CODE,
	   MO.DRUG_NAME,
	   MO.DOSAGE,
	   MO.DOSAGE_UNIT,
	   MO.MEDICINE_FRENQUENCY,
	   MO.PRESCRIPTION_SN,  --用药长期医嘱
	   MO.ORDER_TIME,
	   MO.STOP_TIME,
	   MO.CANCEL_TIME,
	   MO.MEDICINE_FREQ_NAME,
	   MO.SKIN_TEST_RESULT,
	   MO.APPROVED_DRUG_NAME,
	   MO.ROUTE_CODE,
	   MO.ROUTE_NAME,
	   MO.ORDER_START_TIME,
	   MO.SERIAL_NO,
	   MO.MEDICINE_TYPE_NAME,
	   MO.TOTAL_DOSAGE,
	   MO.TOTAL_DOSAGE_UNIT,
	   MO.MEDICINE_FORM
  FROM MEDICATION_ORDER MO
 WHERE MO.VISIT_SN = /*visitSn*/
 	   AND TRUNC(MO.ORDER_START_TIME) <= TO_DATE(/*inpatientDate*/,'YYYY-MM-DD')
   	   AND (MO.STOP_TIME >= TO_DATE(/*inpatientDate*/, 'YYYY-MM-DD')
	    or MO.STOP_TIME IS NULL)
 	   AND MO.TEMPORARY_FLAG = /*longTermFlag*/
 	   AND MO.ORDER_STATUS != /*cancelOrderStatus*/
       AND MO.DELETE_FLAG = '0'
	   AND NOT EXISTS
	          (
	              SELECT 1
	                FROM HIDE_DRUG HD
	               WHERE MO.DRUG_CODE = HD.DRUG_CODE
	                 AND HD.DELETE_FLAG = '0'
	                 and hd.user_name = /*userSn*/
	          )
		ORDER BY MO.ORDER_START_TIME, MO.ORDER_SN DESC
/*END*/
 
/*IF "temporaryDrugOrder".equals(itemFlag)*/
-- 临时药物医嘱
SELECT MO.VISIT_SN,
       MO.ORDER_SN,
       MO.DRUG_CODE,
       MO.DRUG_NAME,
       MO.DOSAGE,
       MO.MEDICINE_FORM,
       MO.DOSAGE_UNIT,
       MO.MEDICINE_FRENQUENCY,
       MO.TOTAL_DOSAGE,
       MO.TOTAL_DOSAGE_UNIT,
	   MO.PRESCRIPTION_SN,NVL(MO.ORDER_START_TIME,MO.ORDER_TIME) INPATIENT_DATE,
	   ROW_NUMBER () OVER (PARTITION BY TRUNC(NVL(MO.ORDER_START_TIME,MO.ORDER_TIME)) ORDER BY MO.ORDER_START_TIME DESC, MO.ORDER_SN DESC) ROW_NUM
  FROM MEDICATION_ORDER MO
 WHERE MO.VISIT_SN = /*visitSn*/
 	   AND NVL(MO.ORDER_START_TIME,MO.ORDER_TIME) BETWEEN TO_DATE(/*inpatientDate*/,'YYYY-MM-DD') AND TO_DATE(/*inpatientDate*/ || '23:59:59', 'YYYY-MM-DD HH24:MI:SS')
 	   AND MO.ORDER_STATUS != /*cancelOrderStatus*/
 	   AND MO.TEMPORARY_FLAG = /*longTermFlag*/
       AND MO.DELETE_FLAG = '0'
   	   AND NOT EXISTS
          (
              SELECT 1
                FROM HIDE_DRUG HD
               WHERE MO.DRUG_CODE = HD.DRUG_CODE
                 AND HD.DELETE_FLAG = '0'
                 and hd.user_name = /*userSn*/
          )
		ORDER BY MO.ORDER_START_TIME DESC, MO.ORDER_SN DESC
/*END*/
	
/*IF "examination".equals(itemFlag)*/
-- 检查
SELECT EO.VISIT_SN,
       ER.EXAM_REPORT_SN,
       EO.EXAM_METHOD_CODE AS EXAMINATION_METHOD,
       EO.EXAM_METHOD_NAME AS EXAMINATION_METHOD_NAME,
       EO.ITEM_CODE AS EXAMINATION_ITEM, --检查
       EO.ITEM_NAME AS EXAMINATION_ITEM_NAME,
       EO.ORDER_TIME INPATIENT_DATE,
       EO.REQUEST_DATE,
       EO.EXEC_DEPT_NAME,
       EO.ORDER_STATUS_NAME,
       ER.WITHDRAW_FLAG,
       EO.PATIENT_SN,
       EO.REGION_CODE AS EXAMINATION_REGION,
       EO.REGION_NAME AS EXAMINATION_REGION_NAME,
       EI.ITEM_SN,
       EI.EXAMINING_DOCTOR_NAME,
       EI.EXAMINATION_METHOD_NAME,
       EI.IMAGING_CONCLUSION AS EI_IMAGING_CONCLUSION,
       EI.IMAGING_FINDING AS EI_IMAGING_FINDING,
       ER.ITEM_CLASS,
       ER.ITEM_CLASS_NAME,
       ER.REPORT_DOCTOR_NAME,
       ER.EXAM_DEPT_NAME,
       ER.IMAGING_FINDING AS ER_IMAGING_CONCLUSION,
       ER.IMAGING_CONCLUSION AS ER_IMAGING_FINDING,
       ER.EXAMINATION_DATE,
       ER.REPORT_MEMO,
       EO.ORDER_SN AS EXAM_ORDER_SN,
       ROW_NUMBER() OVER(PARTITION BY TRUNC(EO.ORDER_TIME) ORDER BY EO.ORDER_TIME DESC, EO.ORDER_SN DESC, ER.EXAM_REPORT_SN DESC, EI.ITEM_SN DESC) ROW_NUM
  FROM EXAMINATION_ORDER EO,
       EXAMINATION_RESULT ER,
       EXAMINATION_ITEM EI,
       EXAM_ORDER_EXAM_RESULT EOER
 WHERE EO.ORDER_SN = EOER.EXAM_ORDER_SN(+)
   AND EOER.EXAM_RESULT_SN = ER.EXAM_REPORT_SN(+)
   AND ER.EXAM_REPORT_SN = EI.EXAM_REPORT_SN(+)
   AND EO.DELETE_FLAG = '0'
   AND EOER.DELETE_FLAG(+) = '0'
   AND ER.DELETE_FLAG(+) = '0'
   AND EI.DELETE_FLAG(+) = '0'
   AND EO.VISIT_SN = /*visitSn*/
   AND EO.ORDER_TIME BETWEEN TO_DATE( /*inpatientDate*/, 'YYYY-MM-DD') AND
       TO_DATE( /*inpatientDate*/ || '23:59:59', 'YYYY-MM-DD HH24:MI:SS')
 ORDER BY EO.ORDER_TIME     DESC,
          EO.ORDER_SN       DESC,
          ER.EXAM_REPORT_SN DESC,
          EI.ITEM_SN        DESC
/*END*/
	
/*IF "lab".equals(itemFlag)*/
-- 检验
SELECT LO.VISIT_SN,
       LRCI.ITEM_CODE,
       LO.ITEM_NAME,
       LO.PATIENT_SN,
       LO.ORDER_STATUS_NAME,
       LR.WITHDRAW_FLAG,
       LR.LAB_REPORT_SN,
       LR.LAB_DEPT,
       LR.TESTER_ID,
       LR.TESTER_NAME,
       LR.TEST_DATE,
       LR.REPORTER_ID,
       LR.REPORTER_NAME AS REPORT_DOCTOR_NAME,
       LR.REPORT_DATE,
       LR.REVIEWER_ID,
       LR.REVIEWER_NAME,
       LR.REVIEW_DATE,
       LR.SAMPLE_TYPE,
       LR.REPORT_MEMO,
       LO.ORDER_TIME INPATIENT_DATE,
       LR.SOURCE_SYSTEM_ID,
       LR.WITHDRAW_FLAG,
       LRCI.COMPOSITE_ITEM_SN,
       LRCI.WARN_FLAG,
       LO.ORDER_SN AS LAB_ORDER_SN,
       LR.LAB_DEPT_NAME,
       ROW_NUMBER() OVER(PARTITION BY TRUNC(LO.ORDER_TIME) ORDER BY LO.ORDER_TIME DESC, LO.ORDER_SN DESC, LR.LAB_REPORT_SN DESC, LRCI.COMPOSITE_ITEM_SN DESC) ROW_NUM
  FROM LAB_ORDER LO,LAB_ORDER_LAB_RESULT LOLR,LAB_RESULT LR,LAB_RESULT_COMPOSITE_ITEM LRCI
 WHERE LO.ORDER_SN = LOLR.LAB_ORDER_SN(+)
   AND LOLR.LAB_REPORT_SN = LR.LAB_REPORT_SN(+)
   AND LR.LAB_REPORT_SN = LRCI.LAB_REPORT_SN(+) 
   AND LO.DELETE_FLAG = '0'
   AND LOLR.DELETE_FLAG(+) = '0'
   AND LR.DELETE_FLAG(+) = '0' 
   AND LRCI.DELETE_FLAG(+) = '0' 
   AND LO.VISIT_SN = /*visitSn*/
   AND LO.ORDER_TIME BETWEEN TO_DATE( /*inpatientDate*/, 'YYYY-MM-DD') AND
       TO_DATE( /*inpatientDate*/ || '23:59:59', 'YYYY-MM-DD HH24:MI:SS')
 ORDER BY LO.ORDER_TIME          DESC,
          LO.ORDER_SN            DESC,
          LR.LAB_REPORT_SN       DESC,
          LRCI.COMPOSITE_ITEM_SN DESC
/*END*/
	
/* $Author :chang_xuewen
  * $Date : 2013/10/24 11:00$
  * [BUG]0038443 MODIFY BEGIN
  */
/*IF "procedure".equals(itemFlag)*/
-- 手术
select po.patient_sn,po.visit_sn,po.order_name,po.order_time INPATIENT_DATE,po.order_sn,
		ROW_NUMBER () OVER (PARTITION BY TRUNC(po.order_time) ORDER BY po.order_sn) ROW_NUM
 	from procedure_order po
 	WHERE po.VISIT_SN = /*visitSn*/
          AND po.order_time BETWEEN TO_DATE( /*inpatientDate*/, 'YYYY-MM-DD') 
		 	   AND TO_DATE( /*inpatientDate*/ || '23:59:59', 'YYYY-MM-DD HH24:MI:SS')
          AND po.DELETE_FLAG = '0'
     ORDER BY po.order_sn DESC
/*END*/

/*IF "proceduredoc".equals(itemFlag)*/
SELECT RES.VISIT_SN,RES.DOCUMENT_NAME,RES.DOCUMENT_TYPE,RES.DOCUMENT_LID,RES.DOCUMENT_TYPE_NAME,RES.WRITE_TIME,RES.DOCUMENT_SN,RES.INPATIENT_DATE,RES.SUBMIT_TIME,
	   RES.DOCUMENT_AUTHOR_NAME
  FROM (
      	SELECT CD.VISIT_SN,CD.DOCUMENT_NAME,CD.DOCUMENT_TYPE,CD.DOCUMENT_LID,CD.DOCUMENT_TYPE_NAME,CD.WRITE_TIME,CD.DOCUMENT_SN,CD.SUBMIT_TIME INPATIENT_DATE,CD.SUBMIT_TIME,  --病例文书
			   CD.DOCUMENT_AUTHOR_NAME,ROW_NUMBER () OVER (PARTITION BY TRUNC(CD.SUBMIT_TIME) ORDER BY CD.SUBMIT_TIME DESC,CD.DOCUMENT_SN DESC) ROW_NUM
		  FROM CLINICAL_DOCUMENT CD
		 WHERE CD.VISIT_SN = /*visitSn*/
		 	   AND CD.WRITE_TIME BETWEEN TO_DATE( /*inpatientDate*/, 'YYYY-MM-DD') 
		 	   AND TO_DATE( /*inpatientDate*/ || '23:59:59', 'YYYY-MM-DD HH24:MI:SS')
		 	   AND CD.DELETE_FLAG = '0'
		 	   AND CD.DOCUMENT_TYPE != '04'
		 	   AND EXISTS (SELECT 1 FROM DUAL WHERE (CD.SERVICE_ID = 'BS329' OR CD.SERVICE_ID = 'BS337' OR CD.SERVICE_ID = 'BS327'))
		UNION ALL
		SELECT CD.VISIT_SN,CD.DOCUMENT_NAME,CD.DOCUMENT_TYPE,CD.DOCUMENT_LID,CD.DOCUMENT_TYPE_NAME,CD.WRITE_TIME,CD.DOCUMENT_SN,CD.SUBMIT_TIME INPATIENT_DATE,CD.SUBMIT_TIME,  --病例文书
         	   CD.DOCUMENT_AUTHOR_NAME,ROW_NUMBER () OVER (PARTITION BY TRUNC(CD.SUBMIT_TIME) ORDER BY CD.SUBMIT_TIME DESC,CD.DOCUMENT_SN DESC) ROW_NUM
      	  FROM CLINICAL_DOCUMENT CD
		 WHERE CD.VISIT_SN = /*visitSn*/
		 	   AND CD.WRITE_TIME BETWEEN TO_DATE( /*inpatientDate*/, 'YYYY-MM-DD') 
		 	   AND TO_DATE( /*inpatientDate*/ || '23:59:59', 'YYYY-MM-DD HH24:MI:SS')
		 	   AND CD.DELETE_FLAG = '0'
		 	   AND CD.DOCUMENT_TYPE != '04'
			   AND (CD.DOCUMENT_NAME LIKE '%术后%' OR CD.DOCUMENT_NAME LIKE '%术前%')
		 	   AND CD.SERVICE_ID = 'BS336'
       ) RES
 ORDER BY RES.SUBMIT_TIME DESC,RES.DOCUMENT_SN DESC
/*END*/
 
/*IF "no_use".equals(itemFlag)*/
-- 手术
SELECT SP.VISIT_SN,
       SP.OPERATION_NAME,
       SP.OPERATION_DATE INPATIENT_DATE,
       SP.SURGICAL_DEPT_NAME,
       SP.PROCEDURE_SN,
       ROW_NUMBER() OVER(PARTITION BY TRUNC(SP.OPERATION_DATE) ORDER BY SP.START_TIME DESC, SP.PROCEDURE_SN DESC) ROW_NUM
  FROM SURGICAL_PROCEDURE SP
 WHERE SP.VISIT_SN = /*visitSn*/
   AND SP.OPERATION_DATE BETWEEN
       TO_DATE( /*inpatientDate*/, 'YYYY-MM-DD') AND
       TO_DATE( /*inpatientDate*/ || '23:59:59', 'YYYY-MM-DD HH24:MI:SS')
   AND SP.DELETE_FLAG = '0'
 ORDER BY SP.START_TIME DESC, SP.PROCEDURE_SN DESC
/*END*/

 /*IF "documentation".equals(itemFlag)*/
-- 病例文书
SELECT RES.VISIT_SN,RES.DOCUMENT_NAME,RES.DOCUMENT_TYPE,RES.DOCUMENT_LID,RES.DOCUMENT_TYPE_NAME,RES.WRITE_TIME,RES.DOCUMENT_SN,RES.INPATIENT_DATE,RES.SUBMIT_TIME,
	   RES.DOCUMENT_AUTHOR_NAME
  FROM (
      	SELECT CD.VISIT_SN,CD.DOCUMENT_NAME,CD.DOCUMENT_TYPE,CD.DOCUMENT_LID,CD.DOCUMENT_TYPE_NAME,CD.WRITE_TIME,CD.DOCUMENT_SN,CD.WRITE_TIME INPATIENT_DATE,CD.SUBMIT_TIME,  --病例文书
			   CD.DOCUMENT_AUTHOR_NAME,ROW_NUMBER () OVER (PARTITION BY TRUNC(CD.SUBMIT_TIME) ORDER BY CD.SUBMIT_TIME DESC,CD.DOCUMENT_SN DESC) ROW_NUM
		  FROM CLINICAL_DOCUMENT CD
		 WHERE CD.VISIT_SN = /*visitSn*/
		 	   AND CD.WRITE_TIME BETWEEN TO_DATE( /*inpatientDate*/, 'YYYY-MM-DD') 
		 	   AND TO_DATE( /*inpatientDate*/ || '23:59:59', 'YYYY-MM-DD HH24:MI:SS')
		 	   AND CD.DELETE_FLAG = '0'
		 	   AND (CD.DOCUMENT_TYPE != '04' OR CD.SERVICE_ID = 'BS337_S006')
		 	   AND NOT EXISTS (SELECT 1 FROM DUAL WHERE (CD.SERVICE_ID = 'BS329' OR CD.SERVICE_ID = 'BS337' OR CD.SERVICE_ID = 'BS336' OR CD.SERVICE_ID = 'BS327'))
		UNION ALL
		SELECT CD.VISIT_SN,CD.DOCUMENT_NAME,CD.DOCUMENT_TYPE,CD.DOCUMENT_LID,CD.DOCUMENT_TYPE_NAME,CD.WRITE_TIME,CD.DOCUMENT_SN,CD.WRITE_TIME INPATIENT_DATE,CD.SUBMIT_TIME,  --病例文书
         	   CD.DOCUMENT_AUTHOR_NAME,ROW_NUMBER () OVER (PARTITION BY TRUNC(CD.SUBMIT_TIME) ORDER BY CD.SUBMIT_TIME DESC,CD.DOCUMENT_SN DESC) ROW_NUM
      	  FROM CLINICAL_DOCUMENT CD
		 WHERE CD.VISIT_SN = /*visitSn*/
		 	   AND CD.WRITE_TIME BETWEEN TO_DATE( /*inpatientDate*/, 'YYYY-MM-DD') 
		 	   AND TO_DATE( /*inpatientDate*/ || '23:59:59', 'YYYY-MM-DD HH24:MI:SS')
		 	   AND CD.DELETE_FLAG = '0'
		 	   AND (CD.DOCUMENT_TYPE != '04' OR CD.SERVICE_ID = 'BS337_S006')
			   AND (CD.DOCUMENT_NAME NOT LIKE '%术后%' AND CD.DOCUMENT_NAME NOT LIKE '%术前%')
		 	   AND CD.SERVICE_ID = 'BS336'
       ) RES
 ORDER BY RES.SUBMIT_TIME DESC,RES.DOCUMENT_SN DESC
/*END*/
/*IF "no_use".equals(itemFlag)*/
-- 病例文书
SELECT CD.VISIT_SN,
       CD.DOCUMENT_NAME,
       CD.DOCUMENT_AUTHOR_NAME,
       CD.DOCUMENT_MODIFIER_NAME,
       CD.DOCUMENT_TYPE,
       CD.DOCUMENT_TYPE_NAME,
       CD.WRITE_TIME,
       CD.DOCUMENT_SN,
       CD.SUBMIT_TIME INPATIENT_DATE,
       CD.SUBMIT_TIME,
       ROW_NUMBER() OVER(PARTITION BY TRUNC(CD.SUBMIT_TIME) ORDER BY CD.SUBMIT_TIME DESC, CD.DOCUMENT_SN DESC) ROW_NUM
  FROM CLINICAL_DOCUMENT CD
 WHERE CD.VISIT_SN = /*visitSn*/
   AND CD.SUBMIT_TIME BETWEEN
       TO_DATE( /*inpatientDate*/, 'YYYY-MM-DD') AND
       TO_DATE( /*inpatientDate*/ || '23:59:59', 'YYYY-MM-DD HH24:MI:SS')
   AND CD.DELETE_FLAG = '0'
 ORDER BY CD.SUBMIT_TIME DESC, CD.DOCUMENT_SN DESC

/*END*/
/*  [BUG]0038443 MODIFY END  */
	
/*IF "noDrugOrder".equals(itemFlag)*/
-- 非药物医嘱
SELECT M.VISIT_SN,M.ORDER_FLAG,M.ORDER_SN,M.ORDER_TITLE,M.ORDER_PATH,RTRIM(M.ORDER_NAME) ORDER_NAME,M.ORDER_TIME,M.ORDER_TYPE,M.ORDER_TIME INPATIENT_DATE,
	   M.ORDER_TYPE,M.ORDER_STATUS_NAME,M.WARD_NAME,M.ORDER_TYPE_NAME
FROM (
		SELECT TOD.VISIT_SN,
		       '1' ORDER_FLAG,
		       TOD.ORDER_SN,
		       '诊疗医嘱详细' ORDER_TITLE,
		       '../order/treatment_' || TOD.ORDER_SN || '.html' ORDER_PATH,
		       TOD.ITEM_NAME ORDER_NAME,
		       TOD.ORDER_TIME,
		       TOD.ORDER_TYPE,
		       TOD.ORDER_STATUS_NAME,
		       TOD.WARD_NAME, --非药物医嘱 --诊疗医嘱
		       TOD.ORDER_TYPE_NAME ORDER_TYPE_NAME
		  FROM TREATMENT_ORDER TOD
		 WHERE TOD.VISIT_SN = /*visitSn*/
		   AND TOD.ORDER_TIME BETWEEN TO_DATE(/*inpatientDate*/,'YYYY-MM-DD') AND TO_DATE(/*inpatientDate*/ || '23:59:59', 'YYYY-MM-DD HH24:MI:SS')
		   AND TOD.DELETE_FLAG = '0'
		 UNION ALL
		SELECT CO.VISIT_SN,
		       '2' ORDER_FLAG,
		       CO.ORDER_SN,
		       '护理医嘱详细' ORDER_TITLE,
		       '../order/care_' || CO.ORDER_SN || '.html' ORDER_PATH,
		       CO.ORDER_NAME,
		       CO.INPUT_TIME ORDER_TIME,
		       CO.ORDER_TYPE, --非药物医嘱 --护理医嘱
		       CO.ORDER_STATUS_NAME,
		       CO.WARDS_NAME AS WARD_NAME,
		       CO.ORDER_TYPE_NAME
		  FROM CARE_ORDER CO
		 WHERE CO.VISIT_SN = /*visitSn*/
		   AND CO.INPUT_TIME BETWEEN TO_DATE(/*inpatientDate*/,'YYYY-MM-DD') AND TO_DATE(/*inpatientDate*/ || '23:59:59', 'YYYY-MM-DD HH24:MI:SS')
		   AND CO.DELETE_FLAG = '0'
		 UNION ALL
	
		SELECT CNO.VISIT_SN,
		       '6' ORDER_FLAG,
		       CNO.ORDER_SN,
		       '会诊医嘱详细' ORDER_TITLE,
		       '../order/consultation_' || CNO.ORDER_SN || '.html' ORDER_PATH,
		       CNO.ORDER_NAME,
		       CNO.ORDER_TIME,
		       CNO.ORDER_TYPE_CODE AS ORDER_TYPE,  --非药物医嘱 --会诊医嘱
		       CNO.ORDER_STATUS_NAME,
		       ''WARD_NAME,
		       CNO.ORDER_TYPE_NAME ORDER_TYPE_NAME
		  FROM CONSULTATION_ORDER CNO
		 WHERE CNO.VISIT_SN = /*visitSn*/
		   AND CNO.ORDER_TIME BETWEEN TO_DATE(/*inpatientDate*/,'YYYY-MM-DD') AND TO_DATE(/*inpatientDate*/ || '23:59:59', 'YYYY-MM-DD HH24:MI:SS')
		   AND CNO.DELETE_FLAG = '0'
		 UNION ALL
		SELECT GLO.VISIT_SN,
		       '7' ORDER_FLAG,
		       GLO.ORDER_SN,
		       '其他医嘱详细' ORDER_TITLE,
		       '../order/general_' || GLO.ORDER_SN || '.html' ORDER_PATH,
		       GLO.ORDER_NAME,
		       GLO.INPUT_TIME ORDER_TIME,
		       GLO.order_type_code as ORDER_TYPE, --非药物医嘱 --其他医嘱
		       GLO.ORDER_STATUS_NAME,
		       GLO.WARD_NAME,
		       GLO.ORDER_TYPE_NAME ORDER_TYPE_NAME
		  FROM GENERAL_ORDER GLO
		 WHERE GLO.VISIT_SN = /*visitSn*/
		   AND GLO.INPUT_TIME BETWEEN TO_DATE(/*inpatientDate*/,'YYYY-MM-DD') AND TO_DATE(/*inpatientDate*/ || '23:59:59', 'YYYY-MM-DD HH24:MI:SS')
		   AND GLO.DELETE_FLAG = '0'
	) M
ORDER BY M.ORDER_TIME DESC, M.ORDER_SN DESC
/*END*/