/**[FUN]V05-101警告通知
 * @version 1.0, 2013/04/22  
 * @author 金鹏
 * @since 1.0 
 * 警告通知获取保存成功的异常或危机检验具体结果内容
 */
SELECT LRCI.ITEM_CODE,LRCI.ITEM_NAME,LRI.ITEM_CODE SUBITEM_CODE,
	   LRI.ITEM_VALUE,LRI.ITEM_UNIT,LRI.UNCOMMON_FLAG,LRI.CRISIS_FLAG,LRI.QUALITATIVE_RESULTS
  FROM LAB_RESULT LR,LAB_RESULT_COMPOSITE_ITEM LRCI,LAB_RESULT_ITEM LRI 
 WHERE LR.LAB_REPORT_SN = LRCI.LAB_REPORT_SN
   AND LRCI.COMPOSITE_ITEM_SN = LRI.LAB_RESULT_COMPOSITE_ITEM_SN
   AND LR.DELETE_FLAG = 0 
   AND LRCI.DELETE_FLAG = 0 
   AND LRI.DELETE_FLAG = 0
   AND LR.LAB_REPORT_LID = /*labReportLid*/
   AND LR.SOURCE_SYSTEM_ID = /*sourceSystemId*/
   AND LR.ORG_CODE = /*orgCode*/
   AND (LRI.UNCOMMON_FLAG = 1 OR LRI.CRISIS_FLAG = 1)
 ORDER BY LRCI.ITEM_CODE 