/**
*[FUN]查询敏感信息审计内容
*@version 1.0, 2013/09/25
*@author jinpeng
*@since 1.0
*/
SELECT SAL.USER_ID,
       SAL.USER_NAME,
       SAL.DEPT_CODE,
       SAL.USE_BEGIN_DATE,
       STL.OPERATION_TIME,
       STL.PATIENT_LID,
       STL.PATIENT_DOMAIN,
       STL.DATA_TYPE_NAME,
       STL.BUSINESS_DATA_NO,
       STL.ITEM_NAME,
       SAL.CLIENT_IP,
       SAL.CLIENT_COMPUTER_NAME,
       STL.AUDIT_LOG_SN,
       STL.ORG_CODE,
       STL.ORG_NAME
  FROM SYSTEM_ACCOUNT_LOG SAL, SYSTEM_AUDIT_LOG STL
 WHERE STL.ACCOUNT_LOG_SN = SAL.ACCOUNT_LOG_SN
   AND SAL.ACCOUNT_LOG_SN = /*accountLogSn*/
   AND STL.BUSINESS_DATA_NO = /*businessDataNo*/
   AND STL.OPERATION_TIME = TO_DATE(/*operationTime*/,'YYYY-MM-DD HH24:MI:SS')
   AND SAL.DELETE_FLAG = 0
   AND STL.DELETE_FLAG = 0