/**
 * $Author :li_shenggen
 * $Date : 2014/04/09 18:53$
 * [FUN]打印就诊日期查询条件
 */        
SELECT VISIT_SN, VISIT_DATE,VISIT_DATE ||  '(' || VISIT_DEPT_NAME || ')' VISIT_DATE_DEPT
FROM (
   SELECT ROW_NUMBER() OVER(PARTITION BY TO_CHAR(VISIT_DATE, 'YYYY-MM-DD') ORDER BY VISIT_DATE DESC) ACOL,
       TO_CHAR(VISIT_DATE, 'YYYY-MM-DD') VISIT_DATE,VISIT_DEPT_NAME,MV.ORG_CODE,MV.PATIENT_SN,
       VISIT_SN
   FROM MEDICAL_VISIT MV
   WHERE DELETE_FLAG = '0'
   AND (EXISTS (SELECT 'X' FROM DIAGNOSIS WHERE DIAGNOSIS.DELETE_FLAG = 0 AND DIAGNOSIS.VISIT_SN  = MV.VISIT_SN)
     OR EXISTS (SELECT 'X' FROM EXAMINATION_ORDER EO WHERE EO.DELETE_FLAG = 0 AND EO.VISIT_SN  = MV.VISIT_SN)
       OR EXISTS (SELECT 'X' FROM LAB_ORDER LO WHERE LO.DELETE_FLAG = 0 AND LO.VISIT_SN  = MV.VISIT_SN)
     OR MV.VISIT_DATE >= TO_DATE(/*sysDate*/''||'00-00-00', 'YYYY-MM-DD HH24:MI:SS'))
     AND MV.VISIT_TYPE_CODE <> /*visitTypeCode*/'03'
       AND PATIENT_SN = /*patientSn*/  
     ORDER BY VISIT_DATE DESC
) MV         