/**
 * [FUN]V05-101时间轴列表
 * @version 1.0, 2012/08/01  
 * @author 金鹏
 * @since 1.0
 * 时间轴列表检索结果中对应的检验具体项目结果 异常信息
 */
SELECT LRI.ITEM_CODE,LRI.ITEM_NAME_CN,LRI.ITEM_VALUE,LRI.ITEM_UNIT,LRI.LOW_VALUE,LRI.HIGH_VALUE,
	   WARN_LOW_VALUE,WARN_HIGH_VALUE
  FROM LAB_ORDER LO,
       LAB_ORDER_LAB_RESULT LOLR,
       LAB_RESULT LR,
       LAB_RESULT_COMPOSITE_ITEM LRCI,
  	   LAB_RESULT_ITEM LRI
 WHERE LO.ORDER_SN = LOLR.LAB_ORDER_SN
   AND LOLR.LAB_REPORT_SN = LR.LAB_REPORT_SN
   AND LR.LAB_REPORT_SN = LRCI.LAB_REPORT_SN
   AND LRCI.COMPOSITE_ITEM_SN = LRI.LAB_RESULT_COMPOSITE_ITEM_SN
   AND LO.DELETE_FLAG = '0'
   AND LOLR.DELETE_FLAG = '0'
   AND LR.DELETE_FLAG = '0'
   AND LRCI.DELETE_FLAG = '0'
   AND LRI.DELETE_FLAG = '0' 
   AND LO.ITEM_CODE = LRCI.ITEM_CODE
   AND LO.ORDER_SN = /*orderSn*/
 
