/**
 * $Author :jin_peng
 * $Date : 2012/11/26 10:45$
 * [BUG]0011851 MODIFY BEGIN
 * $Author :jin_peng
 * $Date : 2012/10/08 15:33$
 * [BUG]0010132 MODIFY BEGIN
 * [FUN]V05-101时间轴列表
 * @version 1.0, 2012/05/21  
 * @author 金鹏
 * @since 1.0
 * 时间轴列表检索结果 
 */
/*IF "visit".equals(itemFlag)*/
SELECT * FROM
(SELECT MV.*,ROWNUM NM 
FROM
(
SELECT MV.VISIT_SN,MV.VISIT_DATE,MV.VISIT_TYPE_code,MV.VISIT_TYPE_Name,MV.VISIT_DEPT_id, MV.VISIT_DEPT_Name,MV.visit_doctor_id, --就诊
 	   MV.VISIT_DOCTOR_NAME,MV.DISCHARGE_DATE,MV.VISIT_TIMES,MV.VISIT_STATUS_CODE,MV.ORG_CODE
  FROM MEDICAL_VISIT MV
 WHERE MV.PATIENT_SN = /*patientSn*/
       AND MV.DELETE_FLAG = '0'
       AND MV.VISIT_TYPE_CODE = /*visitTypeCodeInpatient*/
 
UNION 

SELECT MV.VISIT_SN,MV.VISIT_DATE,MV.VISIT_TYPE_code,MV.VISIT_TYPE_Name,MV.VISIT_DEPT_id, MV.VISIT_DEPT_Name,MV.visit_doctor_id, --就诊
 	   MV.VISIT_DOCTOR_NAME,MV.DISCHARGE_DATE,MV.VISIT_TIMES,MV.VISIT_STATUS_CODE,MV.ORG_CODE
  FROM MEDICAL_VISIT MV
 WHERE MV.PATIENT_SN = /*patientSn*/
       AND MV.DELETE_FLAG = '0'
       AND MV.VISIT_TYPE_CODE != /*visitTypeCodeInpatient*/
       AND (EXISTS (SELECT 1 FROM DIAGNOSIS DS WHERE DS.DELETE_FLAG = '0' AND DS.VISIT_SN = MV.VISIT_SN)
        OR EXISTS (SELECT 1 FROM EXAMINATION_ORDER EO WHERE EO.DELETE_FLAG = '0' AND EO.VISIT_SN = MV.VISIT_SN)
        OR EXISTS (SELECT 1 FROM LAB_ORDER LO WHERE LO.DELETE_FLAG = '0' AND LO.VISIT_SN = MV.VISIT_SN))
/*IF visitDate != null && visitDate.length() != 0*/
 ORDER BY VISIT_DATE
--ELSE
 ORDER BY VISIT_DATE DESC
/*END*/
) MV
WHERE ROWNUM <= /*rowNumEnd*/
)
WHERE NM >= /*rowNumStart*/
/*END*/
/**[BUG]0010132 MODIFY END*/

/*IF "diagnosis".equals(itemFlag)*/
SELECT RES.VISIT_SN,RES.DIAGNOSIS_SN,RES.DISEASE_CODE,RES.DISEASE_NAME,RES.DIAGNOSIS_TYPE_NAME,RES.MAIN_DIAGNOSIS_FLAG
  FROM (
	    SELECT DG.VISIT_SN,DG.DIAGNOSIS_SN,DG.DISEASE_CODE,DG.DISEASE_NAME,DG.DIAGNOSIS_TYPE_NAME,DG.MAIN_DIAGNOSIS_FLAG,
	           ROW_NUMBER () OVER (PARTITION BY DG.VISIT_SN ORDER BY DG.DIAGNOSIS_DATE DESC,DG.DIAGNOSIS_SN DESC) ROW_NUM       
	      FROM DIAGNOSIS DG
	     WHERE DG.VISIT_SN IN /*visitSnList*/(10, 20, 30)
	           AND DG.DELETE_FLAG = '0'
	     ORDER BY DG.DIAGNOSIS_DATE DESC,DG.DIAGNOSIS_SN DESC
    ) RES
 WHERE RES.ROW_NUM <= /*displayCount*/
/*END*/

/*IF "drugOrder".equals(itemFlag)*/
SELECT RES.VISIT_SN,RES.ORDER_SN,RES.DRUG_CODE,RES.DRUG_NAME,RES.DOSAGE,RES.DOSAGE_UNIT,RES.MEDICINE_FRENQUENCY,RES.PRESCRIPTION_SN,RES.ORDER_TYPE,RES.APPROVED_DRUG_NAME
  FROM (
		SELECT MO.VISIT_SN,MO.ORDER_SN,MO.DRUG_CODE,MO.DRUG_NAME,MO.DOSAGE,MO.DOSAGE_UNIT,MO.MEDICINE_FRENQUENCY,MO.PRESCRIPTION_SN,MO.ORDER_TYPE,MO.APPROVED_DRUG_NAME, --用药医嘱
		       ROW_NUMBER () OVER (PARTITION BY MO.VISIT_SN ORDER BY MO.ORDER_TIME DESC, MO.ORDER_SN DESC) ROW_NUM
		  FROM MEDICATION_ORDER MO
		 WHERE MO.VISIT_SN IN /*visitSnList*/(10, 20, 30)
		 	   AND NOT EXISTS
	           (
	               SELECT 1
	                 FROM HIDE_DRUG HD
	                WHERE MO.DRUG_CODE = HD.DRUG_CODE
	                  AND HD.DELETE_FLAG = '0'
	                  and hd.user_name = /*userSn*/
	           )
		       AND MO.DELETE_FLAG = '0'
		 ORDER BY MO.ORDER_TIME DESC, MO.ORDER_SN DESC
       ) RES
 WHERE RES.ROW_NUM <= /*displayCount*/
/*END*/
	
/*IF "examination".equals(itemFlag)*/
SELECT RES.VISIT_SN,RES.EXAM_REPORT_SN,RES.EXAMINATION_METHOD,RES.EXAMINATION_METHOD_NAME,RES.EXAMINATION_ITEM, --检查
	   RES.EXAMINATION_ITEM_NAME,RES.WITHDRAW_FLAG,RES.EXAMINATION_REGION,RES.ITEM_SN,
	   RES.ITEM_CLASS_NAME,RES.REPORT_DOCTOR_NAME,RES.EXAM_DEPT_NAME,RES.IMAGING_FINDING,RES.EXAM_ORDER_SN
  FROM (
		SELECT EO.VISIT_SN,ER.EXAM_REPORT_SN,EO.EXAM_METHOD_CODE AS EXAMINATION_METHOD,EO.EXAM_METHOD_NAME AS EXAMINATION_METHOD_NAME,EO.ITEM_CODE AS EXAMINATION_ITEM, --检查
			   EO.ITEM_NAME AS EXAMINATION_ITEM_NAME,ER.WITHDRAW_FLAG,EO.REGION_CODE AS EXAMINATION_REGION,EI.ITEM_SN,
			   ER.ITEM_CLASS_NAME,ER.REPORT_DOCTOR_NAME,ER.EXAM_DEPT_NAME,ER.IMAGING_FINDING,EO.ORDER_SN AS EXAM_ORDER_SN,
			   ROW_NUMBER () OVER (PARTITION BY EO.VISIT_SN ORDER BY EO.ORDER_TIME DESC,EO.ORDER_SN DESC,ER.EXAM_REPORT_SN DESC,EI.ITEM_SN DESC) ROW_NUM
		  FROM EXAMINATION_ORDER EO,
		       EXAMINATION_RESULT ER,
		       EXAMINATION_ITEM EI,
		       EXAM_ORDER_EXAM_RESULT EOER
		 WHERE EO.ORDER_SN = EOER.EXAM_ORDER_SN(+)
		   AND EOER.EXAM_RESULT_SN = ER.EXAM_REPORT_SN(+)
		   AND ER.EXAM_REPORT_SN = EI.EXAM_REPORT_SN(+) 
		   AND EO.DELETE_FLAG = '0'
		   AND EOER.DELETE_FLAG(+) = '0'
		   AND ER.DELETE_FLAG(+) = '0'
		   AND EI.DELETE_FLAG(+) = '0'
		   AND EO.VISIT_SN IN /*visitSnList*/(10, 20, 30)
		 ORDER BY EO.ORDER_TIME DESC,EO.ORDER_SN DESC,ER.EXAM_REPORT_SN DESC,EI.ITEM_SN DESC
       ) RES
 WHERE RES.ROW_NUM <= /*displayCount*/
/*END*/
 
/*IF "lab".equals(itemFlag)*/
SELECT RES.VISIT_SN,RES.ITEM_CODE,RES.ITEM_NAME,RES.LAB_REPORT_SN,RES.LAB_DEPT,RES.TESTER_ID,RES.TESTER_NAME,RES.TEST_DATE,RES.REPORTER_ID,RES.REPORT_DOCTOR_NAME,
       RES.REPORT_DATE,RES.REVIEWER_ID,RES.REVIEWER_NAME,RES.REVIEW_DATE,RES.SAMPLE_TYPE,RES.REPORT_MEMO,RES.SOURCE_SYSTEM_ID, --检验
       RES.WITHDRAW_FLAG,RES.COMPOSITE_ITEM_SN,RES.WARN_FLAG,RES.LAB_ORDER_SN,RES.LAB_DEPT_NAME
  FROM (
		SELECT LABORDER.*,ROW_NUMBER () OVER (PARTITION BY LABORDER.VISIT_SN ORDER BY LABORDER.ORDER_TIME DESC,LABORDER.LAB_ORDER_SN DESC,LABORDER.LAB_REPORT_SN DESC) ROW_NUM
  		  FROM (
  		SELECT LO.VISIT_SN,NULL AS ITEM_CODE,LO.ITEM_NAME,LR.LAB_REPORT_SN,LR.LAB_DEPT,LR.TESTER_ID,LR.TESTER_NAME,LR.TEST_DATE,LR.REPORTER_ID,LR.REPORTER_NAME AS REPORT_DOCTOR_NAME,
		       LR.REPORT_DATE,LR.REVIEWER_ID,LR.REVIEWER_NAME,LR.REVIEW_DATE,LR.SAMPLE_TYPE,LR.REPORT_MEMO,LR.SOURCE_SYSTEM_ID, --检验
		       LR.WITHDRAW_FLAG,NULL AS COMPOSITE_ITEM_SN,NULL AS WARN_FLAG,LO.ORDER_SN AS LAB_ORDER_SN,LR.LAB_DEPT_NAME,LO.ORDER_TIME,
		       ROW_NUMBER() OVER(PARTITION BY LO.ORDER_SN ORDER BY LR.REPORT_DATE DESC) ACOL
		  FROM LAB_ORDER LO,LAB_ORDER_LAB_RESULT LOLR,LAB_RESULT LR 
		 WHERE LO.ORDER_SN = LOLR.LAB_ORDER_SN(+)
		   AND LOLR.LAB_REPORT_SN = LR.LAB_REPORT_SN(+)
	       AND LO.DELETE_FLAG = '0'
	       AND LOLR.DELETE_FLAG(+) = '0'
	       AND LR.DELETE_FLAG(+) = '0'
		   AND LO.VISIT_SN IN /*visitSnList*/(10, 20, 30)
		 ORDER BY LR.REPORT_DATE DESC )  LABORDER
		 WHERE ACOL = 1
		 ORDER BY LABORDER.ORDER_TIME DESC,LABORDER.LAB_ORDER_SN DESC,LABORDER.LAB_REPORT_SN DESC
       ) RES
 WHERE RES.ROW_NUM <= /*displayCount*/
/*END*/
	
/*IF "procedure".equals(itemFlag)*/
SELECT RES.VISIT_SN,RES.OPERATION_NAME,RES.OPERATION_DATE,RES.PROCEDURE_SN
  FROM (
		SELECT SP.VISIT_SN,SP.operation_Name,SP.plan_exec_time OPERATION_DATE,SP.order_Sn PROCEDURE_SN,  --手术
			   ROW_NUMBER () OVER (PARTITION BY SP.VISIT_SN ORDER BY SP.ORDER_TIME DESC,SP.order_Sn DESC) ROW_NUM
		  FROM procedure_order SP
		 WHERE SP.VISIT_SN IN /*visitSnList*/(10, 20, 30)
		 	   AND SP.DELETE_FLAG = '0'
		 ORDER BY SP.ORDER_TIME DESC,SP.order_Sn DESC
       ) RES
 WHERE RES.ROW_NUM <= /*displayCount*/
/*END*/

/*IF "documentation".equals(itemFlag)*/
SELECT RES.VISIT_SN,RES.DOCUMENT_NAME,RES.DOCUMENT_TYPE,RES.DOCUMENT_LID,RES.DOCUMENT_TYPE_NAME,RES.WRITE_TIME,RES.DOCUMENT_SN,RES.SUBMIT_TIME,
	   RES.SERVICE_ID,RES.DOCUMENT_AUTHOR_NAME
  FROM (
		SELECT CD.VISIT_SN,CD.DOCUMENT_NAME,CD.DOCUMENT_TYPE,CD.DOCUMENT_LID,CD.DOCUMENT_TYPE_NAME,CD.WRITE_TIME,CD.DOCUMENT_SN,CD.SUBMIT_TIME,  --病例文书
			   CD.SERVICE_ID,CD.DOCUMENT_AUTHOR_NAME,ROW_NUMBER () OVER (PARTITION BY CD.VISIT_SN ORDER BY CD.WRITE_TIME DESC,CD.DOCUMENT_SN DESC) ROW_NUM
		  FROM CLINICAL_DOCUMENT CD
		 WHERE CD.VISIT_SN IN /*visitSnList*/(10, 20, 30)
		 	   AND CD.DELETE_FLAG = '0'
		 	   AND (CD.DOCUMENT_TYPE != '04' OR CD.SERVICE_ID = 'BS337_S006')
		 ORDER BY CD.WRITE_TIME DESC,CD.DOCUMENT_SN DESC
 	   ) RES
 WHERE RES.ROW_NUM <= /*displayCount*/
/*END*/
	
/*IF "noDrugOrder".equals(itemFlag)*/
SELECT RES.VISIT_SN,RES.ORDER_FLAG,RES.ORDER_SN,RES.ORDER_TITLE,RES.ORDER_PATH,RES.ORDER_NAME,RES.ORDER_TIME,RES.ORDER_TYPE
  FROM (
		SELECT M.VISIT_SN,M.ORDER_FLAG,M.ORDER_SN,M.ORDER_TITLE,M.ORDER_PATH,RTRIM(M.ORDER_NAME) ORDER_NAME,M.ORDER_TIME,M.ORDER_TYPE,
		       ROW_NUMBER () OVER (PARTITION BY M.VISIT_SN ORDER BY M.ORDER_TIME DESC, M.ORDER_SN DESC) ROW_NUM
		  FROM (
				SELECT TOD.VISIT_SN,'1' ORDER_FLAG,TOD.ORDER_SN,'诊疗医嘱详细' ORDER_TITLE,'../order/treatment_' || TOD.ORDER_SN || '.html' ORDER_PATH,TOD.ITEM_NAME ORDER_NAME,TOD.ORDER_TIME,TOD.ORDER_TYPE  --非药物医嘱 --诊疗医嘱
				  FROM TREATMENT_ORDER TOD
				 WHERE TOD.VISIT_SN IN /*visitSnList*/(10, 20, 30)
				 	   AND TOD.DELETE_FLAG = '0'
				 UNION ALL
				SELECT CO.VISIT_SN,'2' ORDER_FLAG,CO.ORDER_SN,'护理医嘱详细' ORDER_TITLE,'../order/care_' || CO.ORDER_SN || '.html' ORDER_PATH,CO.ORDER_NAME,CO.INPUT_TIME ORDER_TIME,CO.ORDER_TYPE --非药物医嘱 --护理医嘱
				  FROM CARE_ORDER CO
				 WHERE CO.VISIT_SN IN /*visitSnList*/(10, 20, 30)
				       AND CO.DELETE_FLAG = '0'
--				 UNION ALL
--				SELECT PO.VISIT_SN,'3' ORDER_FLAG,PO.ORDER_SN,'手术医嘱详细' ORDER_TITLE,'../order/procedure_' || PO.ORDER_SN || '.html' ORDER_PATH,PO.ORDER_NAME,PO.ORDER_TIME,PO.ORDER_TYPE --非药物医嘱 --手术医嘱
--				  FROM PROCEDURE_ORDER PO
--				 WHERE PO.VISIT_SN IN /*visitSnList*/(10, 20, 30)
--				 	   AND PO.DELETE_FLAG = '0'
				 UNION ALL
				SELECT CNO.VISIT_SN,'6' ORDER_FLAG,CNO.ORDER_SN,'会诊医嘱详细' ORDER_TITLE,'../order/consultation_' || CNO.ORDER_SN || '.html' ORDER_PATH,CNO.ORDER_NAME,CNO.ORDER_TIME,CNO.order_type_code as ORDER_TYPE --非药物医嘱 --会诊医嘱
				  FROM CONSULTATION_ORDER CNO
				 WHERE CNO.VISIT_SN IN /*visitSnList*/(10, 20, 30)
				 	   AND CNO.DELETE_FLAG = '0'
				 UNION ALL
				SELECT GLO.VISIT_SN,'7' ORDER_FLAG,GLO.ORDER_SN,'其他医嘱详细' ORDER_TITLE,'../order/general_' || GLO.ORDER_SN || '.html' ORDER_PATH,GLO.ORDER_NAME,GLO.INPUT_TIME ORDER_TIME,GLO.order_type_code as ORDER_TYPE --非药物医嘱 --其他医嘱
				  FROM GENERAL_ORDER GLO
				 WHERE GLO.VISIT_SN IN /*visitSnList*/(10, 20, 30)
				 	   AND GLO.DELETE_FLAG = '0'
			   ) M
		 ORDER BY M.ORDER_TIME DESC, M.ORDER_SN DESC
       ) RES
 WHERE RES.ROW_NUM <= /*displayCount*/
/*END*/
 /**[BUG]0011851 MODIFY END*/